### PR TITLE
New version - more exhaustive response

### PR DESCRIPTION
**Pull request by einenlum**
Huge changes proposed here :). Sorry if the PR is big, but it was hard to do smaller for this whole refacto.

Changes:

- A **more exhaustive response** (see examples in `tests` and in the *README*). This contains the different meanings (with the translations and the examples for each, including audio) and the examples that are sometimes given by Linguee. This is done through a refacto of the responseTransformer, now built with small other transformers for each part of the page.
- It seems there was a problem with some encoding because Linguee uses ISO-8859-1. **We take care of transforming the response to UTF8**.
- **Not found errors are now handled** (they were not caught before because Linguee sends them as 200).
- We use a **Promise** instead of a callback.
- Tests were refactorized to very easily add new cases, if needed.
- **Inversion of control** (avoid to `require` manually the components) is handled thanks to a tiny homemade DIC.

I think all these changes could make this lib even more useful. If accepted, I think it could be nice to tag a release (0.0.1?) before merging these changes.

### CODE REVIEW

**Comment by felipe-augusto** [comment]
@Einenlum sorry for my delay. I really like the new response, but i think maybe we need to parse some `types`, I was looking and linguee returns:

```js
"type": "v", // I think this means a verb right??
```

But this seems to be collapse only on `lessCommonTranslations`, this is right or am I missing something?

Also, what do you think about maintaining the callback response if people want to use it, but keep returning a promise as a result by default.

**Comment by einenlum** [comment]
Hi @felipe-augusto ! Thank you for your answer.

I was wondering the same for the types (should we do a translator or something?) but the issue is that it depends on the domain given by the user.

If we go to [the french domain](https://www.linguee.fr/english-portuguese/search?source=auto&query=money), we get "money **nom adjectival**" and "money market ***n**".
If we use [the portuguese domain](https://www.linguee.pt/english-portuguese/search?source=auto&query=money) we get "money **substantivo modificador**" and "money market **s**".
If we use [the english domain](https://www.linguee.com/english-portuguese/search?source=auto&query=money) we get "money **noun as adjective**" and "money market **n**". And so on…

So either we consider the english domain as the single source of truth and we build a translator to change "v" to "verb" (and if someone uses a different domain, then we let as it is), or we consider adding a translator for every domain (which is too painful *IMO*), or we let the data returned in the page without translation.

For the Promise thing you mean we could either use it as `linguee.translate('money', {from: 'eng', to: 'por'}, function(response) { console.log(response); });` or `linguee.translate('money', {from: 'eng', to: 'por'}).then(function(response) { console.log(response); });` ? I'm not sure I've seen this case already (how does it behave if we send a callback method **and** we use the then method?) but if it works, why not :).

**Comment by felipe-augusto** [comment]
@Einenlum about the type issue, I think the best would be to lock the english domain and parse only his results, do you think there are any problems of doing this?

About the promise/callback, here's I snippet I took from `mongoose`, I saw them doing the promise or callback thing there (maybe to support old node versions? ), here's for you consideration:

```js
exports.promiseOrCallback = function promiseOrCallback(callback, fn) {
  if (typeof callback === 'function') {
    try {
      return fn(callback);
    } catch (error) {
      return process.nextTick(() => {
        throw error;
      });
    }
  }

  return new Promise((resolve, reject) => {
    fn(function(error, res) {
      if (error != null) {
        return reject(error);
      }
      if (arguments.length > 2) {
        return resolve(Array.prototype.slice.call(arguments, 1));
      }
      resolve(res);
    });
  });
};
```

**Comment by einenlum** [comment]
@felipe-augusto About the domain, I think it makes sense. We could lock it to `https://www.linguee.com` to avoid handling different locales.
Then we could think of a kind of dictionary key: value in each transformer to handle these types. What do you think?

About the promise thing, I'm not sure a `new Promise()` will not throw an error in previous node versions anyway. Is there really any pro to support callback when the advised way to handle async is Promises now? (see [You don't know JS](https://github.com/getify/You-Dont-Know-JS/tree/master/async%20%26%20performance) or [this SO question](https://stackoverflow.com/questions/45041462/node-js-when-to-use-promises-vs-callbacks)).

**Comment by felipe-augusto** [comment]
@Einenlum Sorry for my delay here, do you want this to be merged already or should I wait for more changes?

I think the solution you proposed for the domain is good and we can drop my idea to support callbacks.

**Comment by einenlum** [comment]
@felipe-augusto I will hardcode the domain and create this shortcut translator in the following hours/days. Then we can merge the PR :). Thanks!

**Comment by einenlum** [comment]
@felipe-augusto Done!

I added translation for abbreviations when necessary (sometimes the full meaning is actually given in a toolbox by linguee). Linguee adds non breakable spaces in them (like in "noun, masculine") so I replaced them by normal spaces to ensure homogeneity.

Since there was a tiny bug in the container I realized it would be better to just use the externalized version of it. I made a package [here](https://www.npmjs.com/package/@einenlum/jic) that is fully tested. The pro is to have a DIC working and tested, the con is to add a small dependency to the project. If you don't think it's a good idea, just tell me and I put the homemade version back :).

Apart from that, seems good to merge! :balloon:

**Comment by einenlum** [comment]
@felipe-augusto up? :)

**Comment by felipe-augusto** [comment]
@Einenlum Sorry for my delay, I was on vacation. Seems good to be merged. Thanks!

**Comment by einenlum** [comment]
Thank you very much! :)

**Pull request merged**
